### ISSUE TITLE
What to do about website at Savannah?

### ISSUE THREAD

**Issue by ottok** [rdiff-backup/rdiff-backup.net#1]
The old rdiff-backup website still exists at http://rdiff-backup.nongnu.org/ - something should be done about it.

Maybe review and merge contents with rdiff-backup.net? Or simply add a banner notice there about the new homepage and leave old homepage in place as archive?

**Comment by ottok** [comment]
Could you @davekempe add a banner at the top of http://rdiff-backup.nongnu.org/?

It could saying something like "There is a new website at rdiff-backup.net. Please check it out!". Feel free to write your own text, this was just a quick suggestion.

**Comment by ericzolf** [comment]
Bumping this issue. @davekempe any news? I also noticed that the mailing list needs some love as well, as the footer points to http://rdiff-backup.solutionsfirst.com.au/index.php/RdiffBackupWiki - which doesn't exist anymore.

Can you give me and @ottok admin access to the Savannah stuff?

**Comment by ericzolf** [comment]
I have full admin rights AFAICJ but I'm stuck with CVS and the web site, created https://savannah.nongnu.org/support/?110149 waiting for a reaction from the Savannah team. @davekempe you have been able to modify the web site, any hint what I'm doing wrong?

**Comment by ericzolf** [comment]
OK, the website is now "patched" and links back to the GitHub and the rdiff-backup.net sites. I would suggest that we remove it once the next milestone 2.0.0 has been reached and the packages have hit the road with the new URLs documented. Closing.
