### ISSUE TITLE
related.html contains lots of dead links

### ISSUE THREAD

**Issue by Ma124** [rdiff-backup/rdiff-backup.net#4]
I checked the links in [related.html](https://rdiff-backup.net/docs/) under the heading "Software written for rdiff-backup" and of those the links to `archfs`, `Nagios plugin`, `Keep`, `slbackup`  and `rdiff-backup-tools` were all dead.

**Comment by ericzolf** [comment]
Thanks, we'll look into it, but feel free to offer a Pull Request!
